---
- hosts: k3s-cluster
  become: yes
  tasks:

    - name: Set timezone to Australia/Sydney
      timezone: name=Australia/Sydney

    - name: Update and upgrade existing apt packages
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=latest update_cache=yes
      with_items:
        - figlet
        - toilet
        - nano
        - lsof
        - python3
        - stress
        - rpi-eeprom

    - name: Set MOTD
      copy: src=motd.sh dest=/etc/profile.d/motd.sh

    - name: Update distro and reboot
      apt: upgrade=dist update_cache=yes
      notify:
        - Reboot node

  handlers:
    - name: Reboot node
      reboot:
