---
# TODO: Handler for rebooting on dist upgrade
- hosts: k3s-cluster
  become: yes
  tasks:

    - name: Set timezone
      timezone: name={{ TZ }}

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost webserver'
        state: present

    - name: Update and upgrade existing apt packages
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=latest update_cache=yes
      with_items:
        - figlet
        - toilet
        - nano
        - lsof
        - python3
        - stress

    - name: Set MOTD
      copy: src=motd.sh dest=/etc/profile.d/motd.sh

    - name: Update firmware
      apt: name=rpi-eeprom state=latest update_cache=yes
      # notify:
      #   - reboot node

    - name: Update distro
      apt: upgrade=dist update_cache=yes
  #     notify:
  #       - reboot node
  # handlers:
  #   - name: reboot node
  #     reboot:
