---
- hosts: master
  become: yes
  tasks:
    - name: Configure K3S master
      shell: 'curl -sfL https://get.k3s.io | sh -'
    - name: Return Kubernetes cluster token
      shell: kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
      register: K3S_TOKEN
- hosts: node
  become: yes
  tasks:
    - name: Configure and join K3S nodes
      shell: 'curl -sfL https://get.k3s.io | K3S_URL=https://k3s-master:6443 K3S_TOKEN={{ hostvars.master.K3S_TOKEN }} sh -'
