---
- hosts: master
  become: yes
  tasks:
    - name: Configure K3S master
      shell: 'curl -sfL https://get.k3s.io | sh -'
    - name: Return Kubernetes cluster token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: K3S_TOKEN
- hosts: node
  become: yes
  tasks:
    - name: Configure and K3S nodes and join to the cluster
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://k3s-master:6443 K3S_TOKEN={{hostvars['k3s-master']['K3S_TOKEN']['stdout']}} sh -
      register: out
    # - debug: var=out.stdout_lines
    # - debug: var=out.stderr
