---

- hosts: k3s-master
  become: yes
  tasks:

    - name: Configure master
      shell: 'curl -sfL https://get.k3s.io | sh -'
    - name: Return Kubernetes cluster token
      shell: 'echo "export node_token=$(sudo cat /var/lib/rancher/k3s/server/node-token)"'
    - set_fact: k3s_token="{{ node_token }}"

---

- hosts: k3s-node
  become: yes
  tasks:
    - name: Stuff
      shell: 'curl -sfL https://get.k3s.io | \
              K3S_URL=https://{{ ansible_host }}:6443 \
              K3S_TOKEN={{ k3s_token }} \
              sh -'
