---
- hosts: master
  become: yes
  tasks:
    - name: Configure K3S master
      shell: 'curl -sfL https://get.k3s.io | sh -'
    - name: Return Kubernetes cluster token
      shell: kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
      register: K3S_TOKEN
- hosts: node
  become: yes
  tasks:
    - name: Join nodes to the K3S cluster
      shell: 'curl -sfL https://get.k3s.io | sh -'
    - name: Join
      shell: >
        kubeadm join --token={{ hostvars['k3s-master']['K3S_TOKEN'] }}
